### ISSUE TITLE
Error requiring main thread invoking `startNetverify`

### ISSUE THREAD

**Issue by SandroMachado** [Jumio/mobile-react#2]
This first time I call `startNetverify` I am getting the following error:

```
ExceptionsManager.js:73 Exception 'accessing _cachedSystemAnimationFence requires the main thread' was thrown while invoking startNetverify on target JumioMobileSDK with params (
)
```

![simulator screen shot 1 sep 2017 11 50 50](https://user-images.githubusercontent.com/631739/29967207-7035aa52-8f0d-11e7-873b-54fed379da9e.png)

This is probably related/triggered by the request of the camera permission by the iOS.

**Comment by JumioMobileTeam** [comment]
Dear Sandro,
as we stated in your [pull request](https://github.com/Jumio/mobile-react/pull/3) - we will look into it and if necessary adopt your suggestion with the next release.

best regards,
Jumio Mobile Team
