### ISSUE TITLE
Android customization is missing 

### ISSUE THREAD

**Issue by okanzdmr** [Jumio/mobile-react#21]
For flutter and cordoba plugin android SDK seems fine for UI is customization. React native android SDK has not overridable custom style names. Can we include a res folder and custom style names that extends original ones and replace the themes on manifest file like in flutter plugin .

**Comment by fatihtoker** [comment]
i'm having the same issue. +1

**Comment by onurkenis** [comment]
Any progress on that ticket?

**Comment by kolphi** [comment]
Customization wasn't available yet on iOS, that's why we exluded it also for the React-Native Android SDK.
Due to popular demand, we've now set it up for Android and are already testing the feature. We expect to release a new minor version shortly.

**Comment by bratapfelmus** [comment]
Hello all! 

Version 4.0.1 of the RN plugin is out, which now includes customization for Android. 
--> https://github.com/Jumio/mobile-react#customization
