### ISSUE TITLE
Jumio Verification UI/UX issue for iPhone 11 and above 

### ISSUE THREAD

**Issue by jbagaresgaray** [Jumio/mobile-react#22]
**Description**
Encountered as weird UI/UX issue for JUMIO on iPhone 11 and above version

**Screen Recording**
https://vimeo.com/680705408

**Screenshot**
![image](https://user-images.githubusercontent.com/3625802/155252749-477ee206-93f9-435e-b214-f2cefc2a5b5a.png)

**Jumio Version**
v3.9.2

**Output of npx react-native info**
System:
    OS: macOS 12.0.1
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor             
    Memory: 59.64 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.3 - /usr/local/bin/npm
    Watchman: 2021.11.08.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by bratapfelmus** [comment]
Hello @jbagaresgaray
I assume you're using plugin 3.9.2 or something below? 
This is an issue that occurs for iOS 15 if the customization attribute `disableBlur` is set to `true`.

**Comment by jbagaresgaray** [comment]
@bratapfelmus Yes I'm using the plugin 3.9.2 under iOS 15 as well and also I added the `disableBlur` attribute to `true` for iOS configuration..

This only happens to iOS and not on Android.

![image](https://user-images.githubusercontent.com/3625802/155277296-cdbf1f4c-da33-42ee-ab9c-e6fc11632f0f.png)

**Comment by bratapfelmus** [comment]
@jbagaresgaray this issue has been fixed in 4.0.0. 
(If you want to stay on 3.9.2, a short term workaround would always be to set `disableBlur` to `false` or not use it.)
