### ISSUE TITLE
Issues while running in ios device and simulator

### ISSUE THREAD

**Issue by Sanjib018** [Jumio/mobile-react#23]
We have implemented the jumio and we had followed each and every steps in the documentation still we are facing some issues
Please help me

Below are the issues we are facing

dyld[17995]: Library not loaded: @rpath/SocketIO.framework/SocketIO
  Referenced from: /Users/webskitters/Library/Developer/CoreSimulator/Devices/9161E970-673C-421E-A577-5C05F629080C/data/Containers/Bundle/Application/15E5ADE0-83B5-47DE-A7E5-917F632CA885/rentmyfit.app/Frameworks/iProov.framework/iProov
  Reason: tried: '/Users/webskitters/Library/Developer/Xcode/DerivedData/rentmyfit-gfrwntezsnjhsxebowsxgkgvgqmf/Build/Products/Debug-iphonesimulator/SocketIO.framework/SocketIO' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/SocketIO.framework/SocketIO' (no such file), '/usr/lib/swift/SocketIO.framework/SocketIO' (no such file), '/Users/webskitters/Library/Developer/CoreSimulator/Devices/9161E970-673C-421E-A577-5C05F629080C/data/Containers/Bundle/Application/15E5ADE0-83B5-47DE-A7E5-917F632CA885/rentmyfit.app/Frameworks/SocketIO.framework/SocketIO' (no such file), '/Users/webskitters/Library/Developer/CoreSimulator/Devices/9161E970-673C-421E-A577-5C05F629080C/data/Containers/Bundle/Application/15E5ADE0-83B5-47DE-A7E5-917F632CA885/rentmyfit.app/Frameworks/iProov.framework/Frameworks/SocketIO.framework/SocketIO' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/SocketIO.framework/SocketIO' (no such file), '/usr/lib/swift/SocketIO.framework/SocketIO' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/SocketIO.framework/SocketIO' (no such file), '/usr/lib/swift/SocketIO.framework/SocketIO' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/SocketIO.framework/SocketIO' (no such file), '/usr/lib/swift/SocketIO.framework/SocketIO' (no such file), '/Users/webskitters/Library/Developer/CoreSimulator/Devices/9161E970-673C-421E-A577-5C05F629080C/data/Containers/Bundle/Application/15E5ADE0-83B5-47DE-A7E5-917F632CA885/rentmyfit.app/Frameworks/SocketIO.framework/SocketIO' (no such file), '/Users/webskitters/Library/Developer/CoreSimulator/Devices/9161E970-673C-421E-A577-5C05F629080C/data/Containers/Bundle/Application/15E5ADE0-83B5-47DE-A7E5-917F632CA885/rentmyfit.app/Frameworks/SocketIO.framework/SocketIO' (no such file), '/Users/webskitters/Library/Developer/CoreSimulator/Devices/9161E970-673C-421E-A577-5C05F629080C/data/Containers/Bundle/Application/15E5ADE0-83B5-47DE-A7E5-917F632CA885/rentmyfit.app/Frameworks/SocketIO.framework/SocketIO' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/SocketIO.framework/SocketIO' (no such file), '/usr/lib/swift/SocketIO.framework/SocketIO' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/SocketIO.framework/SocketIO' (no such file), '/usr/lib/swift/SocketIO.framework/SocketIO' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/SocketIO.framework/SocketIO' (no such file), '/usr/lib/swift/SocketIO.framework/SocketIO' (no such file), '/Users/webskitters/Library/Developer/CoreSimulator/Devices/9161E970-673C-421E-A577-5C05F629080C/data/Containers/Bundle/Application/15E5ADE0-83B5-47DE-A7E5-917F632CA885/rentmyfit.app/Frameworks/SocketIO.framework/SocketIO' (no such file), '/Users/webskitters/Library/Developer/CoreSimulator/Devices/9161E970-673C-421E-A577-5C05F629080C/data/Containers/Bundle/Application/15E5ADE0-83B5-47DE-A7E5-917F632CA885/rentmyfit.app/Frameworks/SocketIO.framework/SocketIO' (no such file), '/Users/webskitters/Library/Developer/CoreSimulator/Devices/9161E970-673C-421E-A577-5C05F629080C/data/Containers/Bundle/Application/15E5ADE0-83B5-47DE-A7E5-917F632CA885/rentmyfit.app/Frameworks/SocketIO.framework/SocketIO' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/SocketIO.framework/SocketIO' (no such file)
Library not loaded: @rpath/SocketIO.framework/SocketIO
  Referenced from: /Users/webskitters/Library/Developer/CoreSimulator/Devices/9161E970-673C-421E-A577-5C05F629080C/data/Containers/Bundle/Application/15E5ADE0-83B5-47DE-A7E5-917F632CA885/rentmyfit.app/Frameworks/iProov.framework/iProov
  Reason: tried: '/Users/webskitters/Library/Developer/Xcode/DerivedData/rentmyfit-gfrwntezsnjhsxebowsxgkgvgqmf/Build/Products/Debug-iphonesimulator/SocketIO.framework/SocketIO' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/SocketIO.framework/SocketIO' (no such file), '/usr/lib/swift/SocketIO.framework/SocketIO' (no such file), '/Users/webskitters/Library/Developer/CoreSimulator/Devices/9161E970-673C-421E-A577-5C05F629080C/data/Containers/Bundle/Application/15E5ADE0-83B5-47DE-A7E5-917F632CA885/rentmyfit.app/Frameworks/SocketIO.framework/SocketIO' (no such file), '/Users/web
(lldb) 

this is the pod file

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'rentmyfit' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'rentmyfitTests' do
    inherit! :complete
    # Pods for testing
  end
  pod 'Firebase/Analytics'
  pod 'GoogleSignIn', '~> 6.0.2'
  

  use_flipper!()

dynamic_frameworks = ['Socket.IO-Client-Swift', 'Starscream', 'iProov']

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if !dynamic_frameworks.include?(pod.name)
      puts "Overriding the static_framework? method for #{pod.name}"
      def pod.static_framework?;
        true
      end
      def pod.build_type;
        Pod::BuildType.static_library
      end
    end
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
end

![Screenshot 2022-04-15 at 4 30 27 PM](https://user-images.githubusercontent.com/103734855/163564176-ff0a391b-30e3-440e-979b-ea0a2c327ad3.png)

**Comment by bratapfelmus** [comment]
Hello @Sanjib018 
please make sure to run `pod install` again after adding the pre and post install hook to your Podfile.
If this does not resolve the issue, please contact Jumio support --> https://github.com/Jumio/mobile-react#support
