### ISSUE TITLE
Missing workflowExecution parameter in JumioResponse.

### ISSUE THREAD

**Issue by sebikap-gm2** [Jumio/mobile-react#36]
Using the library, I need to retrieve the workflowExecution parameter from the response.
I've tried to open a PR with a proposal to fix this issue, but I don't have permissions.

## Proposed solution - Android - JumioMoudle.kt:
line 108 - after `credentialInfoList?.let { ... }` 
```
val workflowExecutionId = jumioResult.workflowExecutionId
workflowExecutionId?.let{
   result.putString("workflowExecutionId", it)
}
```

## Proposed solution - iOS - JumioMobileSDK.swift:
In function `handleResult`, after `let credentialInfos = jumioResult.credentialInfos`
line 128 `let executionFlowId = jumioResult.executionFlowId`

line 131
```
var body: [String: Any?] = [
   "accountId": accountId,
   "executionFlowId": executionFlowId,
]
```

Thank you!

**Comment by BernadetteTh** [comment]
Hello @sebikap-gm2 
thanks for bringing this to our attention, solution will be included in 4.3.0
