### ISSUE TITLE
When shipping to TestFlight Jumio never finishes loading

### ISSUE THREAD

**Issue by duro** [Jumio/mobile-react#38]
We have the Jumio SDK integrated, and tested it heavily by sending Release builds to Firebase App Distribution. These builds launch the Jumio UI with no trouble.

However when we send up the exact same commit, also done as a Release build, with the only difference in our build process that we use the AppStore provisioning profile instead of the AdHoc profile, when it is tested on TestFlight, the Jumio UI launches, but never continues past "Loading"

We have made sure all the steps that are mentioned here are followed:

https://github.com/Jumio/mobile-react#ios-runs-on-debug-crashes-on-release-build

We are not getting any kind of build errors or crashes, just a hung "Loading" screen.

We have no EventError, or EventResult events coming out either.

We are are at a bit of a loss on what could be causing this, or how to even debug this further.

This is the screen that never goes away...

![IMG_C7206522FB4D-1](https://user-images.githubusercontent.com/17632/193386718-8316e191-1863-4762-8676-11e9b83df858.jpeg)

**Comment by BernadetteTh** [comment]
Hello @duro 
please consider if this might be the cause of the issue --> https://github.com/Jumio/mobile-react#ios-runs-on-debug-crashes-on-release-build

**Comment by BernadetteTh** [comment]
Hello @duro 
any updates on this issue from your end?
