### ISSUE TITLE
Jumio restart app when it is canceled instead of closing the modal

### ISSUE THREAD

**Issue by rebirthtobi** [Jumio/mobile-react#39]
Version: Latest
RN: 0.68.2

Issue:
When Jumio close button is press when capturing of document is not yet started, the modal is closed and user find itself in the previous page. However, when jumio close button is pressed after first capturing or on the capture screen or after successful upload, the app restart.

Desired Implementation:
When jumio close button is pressed, it should always close modal and not restarted the app.

**Comment by rebirthtobi** [comment]
@kolphi i believe you mean line 61 `implementation "com.jumio.android:docfinder:${SDK_VERSION}"` and it woks, thanks

**Comment by kolphi** [comment]
@rebirthtobi We just released version 4.3.1 containing exactly that fix - https://github.com/Jumio/mobile-react/releases/tag/v4.3.1
