### ISSUE TITLE
[ANDROID] Jumio Plugin crashes when "react-native-device-info" is in the project

### ISSUE THREAD

**Issue by matias91** [Jumio/mobile-react#4]
**Project:**

React Native project created with [Ignite](https://github.com/infinitered/ignite)

**Device:**

Samsung Galaxy S8. Model number: SM-G950F
Android 7.0

**Feature:**

Netverify

**Problem:**

The Netverify feature crashes in the "take a selfie" step and the app restarts without showing an error.

**Solution:**

Uninstalling the [react-native-device-info](https://github.com/rebeccahughes/react-native-device-info) plugin seems to work for now, but is a strange solution.

**Aclarations:**

* I followed all the steps of the setup, and also i searched for differences in the files of the **demoApp**.
* I tried removing plugins because it was the only difference with the demo that i found.

**Comment by JumioMobileTeam** [comment]
Dear Matias,
thanks for reaching out to us with your change proposal. As Github is primarily the provider for offering our SDK and documentation in release state, we will not be able to process your request within Github. Code changes are solely being done in our internal repositories.

Please contact our support at support@jumio.com and report this issue with all the information that you provided above.
If possible, please include the stacktrace or any additional information for the crash. Handling the issue via a support request ensures that the issue will be properly documented and processed and also benefits other customers with faster resolutions on similar problems.

best regards,
Jumio Mobile Team
