### ISSUE TITLE
The app does not run on older versions of iOS

### ISSUE THREAD

**Issue by idutka** [Jumio/mobile-react#41]
Hi,

After integrating Jumio into our app we cannot run the app on older versions of iOS (12.4). Everything works fine on the latest version of iOS (16.0). Previously we were able to run the app on all versions of iOS.

The issue also can be reproduced with the [DemoApp](https://github.com/Jumio/mobile-react/tree/master/DemoApp)
DemoApp works fine on the latest versions of iOS but doesn't run on older versions of iOS.

The DemoAppapp crashes on iOS 12.4 with an error:

```
dyld: Library not loaded: /System/Library/Frameworks/Combine.framework/Combine
  Referenced from: /Users/test/Library/Developer/CoreSimulator/Devices/ED460351-0CA7-44EE-A190-61F2658AF5EB/data/Containers/Bundle/Application/5AE1144A-99CB-4A38-A704-00749F5B4BBD/DemoApp.app/Frameworks/Jumio.framework/Jumio
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_FRAMEWORK_PATH=/Users/test/Library/Developer/Xcode/DerivedData/DemoApp-ajxexdtcyexqlgclbcmjzniicjby/Build/Products/Debug-iphonesimulator
DYLD_FALLBACK_LIBRARY_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib
DYLD_ROOT_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot
DYLD_FALLBACK_FRAMEWORK_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks
DYLD_INSERT_LIBRARIES=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib:/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFramew
(lldb) 
```

**Comment by BernadetteTh** [comment]
Hello @idutka 
does this happen when trying to run on the simulator or actual devices as well?

Please be aware that the simulator will only work for the latest iOS version --> https://github.com/Jumio/mobile-sdk-ios#general-requirements

**Comment by idutka** [comment]
Hi @BernadetteTh
Yes, it happens when trying to run on the simulator. 
I don't have actual devices with the old iOS so not able to check.

Probably it is the root of the issue.
Thanks.
