### ISSUE TITLE
Option to set preselectedCountry and cameraPosition is missing started on version 4

### ISSUE THREAD

**Issue by jbagaresgaray** [Jumio/mobile-react#46]
on Jumio v3.9.2 there's an option for `configuration.options` to pass along side `initNetVerify` for `preselectedCountry`. This option was missing on version 4 which I think is essential for setting up default `Check issuing country`. 

Aside from that `cameraPosition` is also missing.

Can this be added back as this was an important feature from your previous version?

**Comment by BernadetteTh** [comment]
Hi @jbagaresgaray 
the attributes aren't missing, as of SDK 4.4.0 SDK configuration works differently
Configuration isn't specified during SDK initialization anymore but already happens before, during the creation of the sdk.token

When the init happens, all preconfigured information is already contained in `<AUTHORIZATION_TOKEN>`
`JumioMobileSDK.initialize(<AUTHORIZATION_TOKEN>, <DATACENTER>);`

Please refer to the Authentication section of our guides for more detailed information --> 
https://github.com/Jumio/mobile-sdk-android#authentication-and-encryption 
https://github.com/Jumio/mobile-sdk-ios#authentication-and-encryption
