### ISSUE TITLE
4.4.0 not building ANDROID

### ISSUE THREAD

**Issue by lmasneri** [Jumio/mobile-react#49]
I've done exactly the installation guide:
`npx react-native@0.68.6 init TestingJumioLastVersion --version 0.68.6`
`yarn add https://github.com/Jumio/mobile-react.git#v4.4.0`

Then the specific setup for android then after doing a build for android this is the error I have:

```
Could not determine the dependencies of task ':react-native-jumio-mobilesdk:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-jumio-mobilesdk:debugCompileClasspath'.
   > Could not find com.jumio.android:core:4.4.1.
     Required by:
         project :react-native-jumio-mobilesdk
   > Could not find com.jumio.android:linefinder:4.4.1.
     Required by:
         project :react-native-jumio-mobilesdk
   > Could not find com.jumio.android:mrz:4.4.1.
     Required by:
         project :react-native-jumio-mobilesdk
   > Could not find com.jumio.android:nfc:4.4.1.
     Required by:
         project :react-native-jumio-mobilesdk
   > Could not find com.jumio.android:barcode:4.4.1.
     Required by:
         project :react-native-jumio-mobilesdk
   > Could not find com.jumio.android:barcode-mlkit:4.4.1.
     Required by:
         project :react-native-jumio-mobilesdk
   > Could not find com.jumio.android:iproov:4.4.1.
     Required by:
         project :react-native-jumio-mobilesdk
   > Could not find com.jumio.android:defaultui:4.4.1.
     Required by:
         project :react-native-jumio-mobilesdk
   > Could not find com.jumio.android:datadog:4.4.1.
     Required by:
         project :react-native-jumio-mobilesdk
   > Could not find com.iproov.sdk:iproov:8.1.0.
     Required by:
         project :react-native-jumio-mobilesdk
```

If I can have some help please!

Thank you

**Comment by BernadetteTh** [comment]
Hello @lmasneri 
please contact [Jumio support](https://github.com/Jumio/mobile-react#contact).

If possible, please add the results of your yarn command to your inquiry, it looks like the plugin didn't install correctly.

**Comment by tombotley** [comment]
Was a solution found for this issue? I am also encountering the same errors.

**Comment by BernadetteTh** [comment]
Hello @tombotley 

SDK version upgrades and adding our repository explicitly to the `build.gradle` fixed the issues on our end.
See this commit --> https://github.com/kolphi/TestingJumioLastVersion/commit/9aaa2bea071f4da22ceebcabaf1db9e7ee1b67ef 

Haven't gotten feedback from the initial customer yet on whether this also fixed it on their end or not.
