### ISSUE TITLE
 Could not find com.jumio.android:core:4.5.0.

### ISSUE THREAD

**Issue by RameeshKp** [Jumio/mobile-react#53]
Here is my android/build.gradle 
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        androidXCore = "1.6.0"
        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
        exclusiveContent {
  forRepository {
    maven {
      url 'https://repo.mobile.jumio.ai'
    }
  }
  filter {
    includeGroup "com.jumio.android"
    includeGroup "com.iproov.sdk"
  }
}
    }
    dependencies {
        classpath 'com.google.gms:google-services:4.3.10' //for firebase
         classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1' // for crashlytics
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
    }
    subprojects { subproject ->
        if(project['name'] == 'react-native-reanimated'){
            project.configurations { compile { } }
        }
}
}
def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())

my react native version is 0.72.0

**Comment by BernadetteTh** [comment]
Hello @RameeshKp 
- which version of `com.android.tools.build:gradle` library are you using? 
- are you using Proguard? Does this issue still happen if you include [Jumio-specific Proguard rules](https://github.com/Jumio/mobile-sdk-android#proguard) 
- Could you share your app build.gradle file? 
- Which steps did you take to add the Jumio plugin before trying to build the project?
