### ISSUE TITLE
Unable to Run Jumio SDK with New Arch Version 0.72.0, Android Build fails with jumio with newArchEnabled = true,

### ISSUE THREAD

**Issue by Rajesh-bex** [Jumio/mobile-react#55]
I am currently facing an issue with running the Jumio SDK after updating to the new Arch version 0.72.0. The SDK worked fine with the previous Arch version, but after upgrading, I encountered compatibility problems.

Steps to Reproduce:

Update the Arch version to 0.72.0 in the project dependencies.
Attempt to run the app that integrates the Jumio SDK.
Observe the error or unexpected behavior.
Expected Behavior:
The Jumio SDK should function properly with the updated Arch version 0.72.0.

Actual Behavior:
The Jumio SDK is not working as expected with the new Arch version. It either throws an error during runtime or exhibits unexpected behavior.

Environment:

Jumio SDK version: 3.9.2
Arch version: 0.72.0
Development environment: visual code, React native- android
Error Messages or Logs:
please find the attachment 
<img width="1552" alt="Screenshot 2023-07-13 at 8 14 47 AM" src="https://github.com/Jumio/mobile-react/assets/83812912/aa2e8511-9ec8-4765-8ae4-34a7396cb84d">

This issue prevents me from using the Jumio SDK effectively in my application with the new Arch version. I kindly request assistance in resolving this compatibility problem. Thank you for your support!

**Comment by BernadetteTh** [comment]
Hi @Rajesh-bex 
the error log you shared clearly shows that the build process is trying to resolve Jumio SDK 3.9.2 dependencies -- if you are using SDK version 4.3.0, these dependencies should not be included anymore. 
Please check which SDK version you have included, could be that something is still cached after an update.

**Comment by Rajesh-bex** [comment]
hi @BernadetteTh : i am trying with different versions from 3.9.2 , please find the version 4.3.0 logs. Please let me know if any thing is required. 

<img width="1552" alt="Screenshot 2023-07-13 at 2 33 13 PM" src="https://github.com/Jumio/mobile-react/assets/83812912/2808da82-41c6-4145-8143-73804181a917">

**Comment by Rajesh-bex** [comment]
Hi @BernadetteTh : we are using 3.9.2 version as it is the latest version supported by the Jumio Client - EML, Please help us to make React native latest version working with that

**Comment by BernadetteTh** [comment]
@Rajesh-bex 
for further assistance with this issue, please contact Jumio support --> https://github.com/Jumio/mobile-react#contact
